// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2OeLhC02Z0zljm-OxeJN_ES7Q7E9JLdk',
    appId: '1:135128060507:web:6fccafba38ad9e36d6257e',
    messagingSenderId: '135128060507',
    projectId: 'flutter-crud-application-a295c',
    authDomain: 'flutter-crud-application-a295c.firebaseapp.com',
    databaseURL: 'https://flutter-crud-application-a295c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-a295c.firebasestorage.app',
    measurementId: 'G-NR06CRXPZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcopB6xYWcZtqiYnthtTDa_BF8hDBkT0Y',
    appId: '1:135128060507:android:6a8705bf18aef987d6257e',
    messagingSenderId: '135128060507',
    projectId: 'flutter-crud-application-a295c',
    databaseURL: 'https://flutter-crud-application-a295c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-a295c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvApMrUNRsRuetg3NrmbQ-woNyr4xFBJ4',
    appId: '1:135128060507:ios:dc0ce3ef73b415b9d6257e',
    messagingSenderId: '135128060507',
    projectId: 'flutter-crud-application-a295c',
    databaseURL: 'https://flutter-crud-application-a295c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-a295c.firebasestorage.app',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvApMrUNRsRuetg3NrmbQ-woNyr4xFBJ4',
    appId: '1:135128060507:ios:dc0ce3ef73b415b9d6257e',
    messagingSenderId: '135128060507',
    projectId: 'flutter-crud-application-a295c',
    databaseURL: 'https://flutter-crud-application-a295c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-a295c.firebasestorage.app',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2OeLhC02Z0zljm-OxeJN_ES7Q7E9JLdk',
    appId: '1:135128060507:web:5c3e77fa27d67019d6257e',
    messagingSenderId: '135128060507',
    projectId: 'flutter-crud-application-a295c',
    authDomain: 'flutter-crud-application-a295c.firebaseapp.com',
    databaseURL: 'https://flutter-crud-application-a295c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-a295c.firebasestorage.app',
    measurementId: 'G-SHP73DTTKQ',
  );
}
